version: '1.0'

stages:
  - MainClone
  - Lint
  - SecurityScan
  - SendEmail

steps:
  MainClone:
    title: Clone main repository
    type: git-clone
    repo: https://github.com/kfface/WMcasestudy.git
    revision: ${{ BRANCH_TAG }}
  
  Lint:
    title: 'RuboCop Lint'
    image: ruby:latest
    working directory: ./ruby_directory
    comands:
      - gem install rubocop
      -rubocop -a .
      #the -a here allows for automatic style correction
  
  SecurityScan:
    title: 'Brakeman Dependency Scan'
    image: ruby:latest
    commands:
      - gem install brakeman
      - brakeman -o output/report.json
      - python3 bmparser.py output/report.json
      - python3 pullrequest.py output/vulnerabilites.csv

  SendEmail:
    type: smtp
    arguments:
      TO: user@wm.com
      FROM: databot@wm.com
      SUBJECT: 'Build for ${{WMcasestudy}}'
      BODY: '<html><a href="${{codfresh.io/WMcasestudy/id={uniquecodefreshid}}}">Here is your requested data</a></html>'
      MIME_TYPE: html
      SMTP_SERVER: smtp.domain.com
      SMTP_USERNAME: databot@wm.com
      SMTP_PASSWORD: ${{ password }}
      ATTACHMENTS:
      - path: ./knownVulnerabilities.csv

