version: '1.0'

stages:
  - MainClone
  - Lint
  - SecurityScan
  - SendEmail
  - DeployToEks

steps:
  MainClone:
    title: Clone main repository
    type: git-clone
    repo: https://github.com/kfface/WMcasestudy.git
    revision: ${{ BRANCH_TAG }}
  
  Lint:
    title: 'RuboCop Lint'
    image: ruby:latest
    working directory: ./ruby_directory
    comands:
      - gem install rubocop
      -rubocop -a .
      #the -a here allows for automatic style correction
  
  SecurityScan:
    title: 'Brakeman Dependency Scan'
    image: ruby:latest
    commands:
      - gem install brakeman
      - brakeman -o report.json
      - python3 bmparser.py report.json
      - python3 pullrequest.py vulnerabilites.csv
        continue-on-error: true
    volumes:
      - .codefresh/volume

  SendEmail:
    type: smtp
    arguments:
      TO: user@wm.com
      FROM: databot@wm.com
      SUBJECT: 'Build for ${{WMcasestudy}}'
      BODY: '<html><a href="${{codfresh.io/WMcasestudy/id={uniquecodefreshid}}}">Here is your requested data</a></html>'
      MIME_TYPE: html
      SMTP_SERVER: smtp.domain.com
      SMTP_USERNAME: databot@wm.com
      SMTP_PASSWORD: ${{ password }}
      ATTACHMENTS:
      - path: ./knownVulnerabilities.csv

  
  DeployToEks:
    type: eks-bluegreen-deploy
    arguments:
      AWS_DEFAULT_REGION: 'us-west-2'
      AWS_ACCESS_KEY_ID: '${{AWS_ACCESS_KEY_ID}}'
      AWS_SECRET_ACCESS_KEY: '${{AWS_SECRET_ACCESS_KEY}}'
      CLUSTER_NAME: WMcasestudy_cluster
      SERVICE_NAME: WMcasestudy
      IMAGE: 'WMcasestudy:latest'
      CODEDEPLOY_APPLICATION: 'AppEKS-${WMcasestudy_cluster}-${WMcasestudy}'
      CODEDEPLOY_DEPLOYMENT_GROUP: 'DgpEKS-${WMcasestudy_cluster}-${WMcasestudy}'
      MAX_WAIT_TIME: 60
    when:

