version: '1.0'

stages:
  - MainClone
  - ZapScan
  - SetEnvironmentVar
  - DeployToEKS

steps:
  MainClone:
    title: Clone main repository
    type: git-clone
    repo: https://github.com/kfface/WMcasestudy.git
    revision: ${{CF_REVISION}}

  ZapScan:
    title: OWASP ZAP FULL Scan
    type: composition
    composition:
      version: '2'
      services:
        zap:
          image: owasp/zap2docker-stable
          ports:
            - '8080:8080'
          environment:
            - API_KEY=your-api-key
            - TARGET_URL=http://WMcasestudy.com
            - ZAP_PORT=8080
            - ZAP_API_KEY=your-api-key
            - ZAP_HEADLESS=true
            - ZAP_ATTACK_MODE=true
          command: zap-full-scan.py -t ${TARGET_URL} -f openapi -O -z '-config api.disablekey=true' -r zap_report.json --output-format json
      steps:
        - title: Wait for ZAP to start
          type: freestyle
          command: sleep 30
        - title: Run ZAP scan
          type: freestyle
          command: |
            zap-cli --zap-url http://localhost:8080/ -p 8080 openapi.load \
              --spec kfface/WMcasestudy/latest/openapi.yaml \
              --name 'WMcasestudy' \
              --hook=/zap-full-scan.py \
              --hook-timeout=300000 \
              --hook-retry-amount=5 \
              --hook-retry-wait=60000

  SetEnvironmentVar:
    title: Set vulnerability count variable
    image: alpine:3.12
    commands:
      - VULN_COUNT=$(wc -l < knownVulnerabilities.csv)
  
  DeployToEks:
    type: eks-bluegreen-deploy
    arguments:
      AWS_DEFAULT_REGION: 'us-west-2'
      AWS_ACCESS_KEY_ID: '${{AWS_ACCESS_KEY_ID}}'
      AWS_SECRET_ACCESS_KEY: '${{AWS_SECRET_ACCESS_KEY}}'
      CLUSTER_NAME: WMcasestudy_cluster
      SERVICE_NAME: WMcasestudy
      IMAGE: 'WMcasestudy:latest'
      CODEDEPLOY_APPLICATION: 'AppEKS-${WMcasestudy_cluster}-${WMcasestudy}'
      CODEDEPLOY_DEPLOYMENT_GROUP: 'DgpEKS-${WMcasestudy_cluster}-${WMcasestudy}'
      MAX_WAIT_TIME: 60
    when:
      condition:
        all:
          - ${{ env.VULN_COUNT }} < 5

